local_backend: true

backend:
  name: git-gateway

i18n:
  structure: multiple_folders
  locales: [en, ru]
  default_locale: en



media_folder: public/media
public_folder: /media

collections:
  - name: "publications"
    i18n: true
    label: "Publications"
    folder: "content/publications"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true, i18n: true }
      - { label: "Date", name: "date", widget: "datetime",  required: true, i18n: true }
      - { label: "Short Description", name: "description", widget: "string", required: true, i18n: true }
      - { label: "Body", name: "body", widget: "markdown",  required: true, i18n: true }
      - label: "Cover Photo"
        name: "cover"
        i18n: true
        required: false
        widget: "file"
        media_library:
          config:
            multiple: false
            max_file_size: 1024000
      - label: "PDF File"
        name: "pdf"
        i18n: true
        required: false
        widget: "file"
        media_library:
          config:
            multiple: false
            max_file_size: 1024000